### ISSUE TITLE
providers should allow more than one type of agent

### ISSUE THREAD

**Issue by dudadornelles** [dudadornelles/hop#15]
the `agents` value in `hop.yml` should be a more complex object:

```yaml
agents_prefix: hop-agent # this used to be inside the agents key
agents:
    gocdhop/hop-agent:
        instances: 2
    otherrepo/specialized-agents:
        instances: 1
        tags: specialized
```
