### ISSUE TITLE
manage role mapping

### ISSUE THREAD

**Issue by dudadornelles** [dudadornelles/hop#20]
either adding a `roles` field to hop.yml or having a `roles.yml` in the root.

```yaml
roles:
  - developer:
    - dev1
    - dev2
    - admin

  - deploy-to-production:
    - dev2

  - admin:
    - admin
```
